-- Supabase Database Setup for AI Bobblehead
-- Run this in your Supabase SQL Editor (safe to re-run)

-- 1. Create the orders table
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tier INT NOT NULL,
    amount INT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    credits_total INT NOT NULL DEFAULT 1,
    credits_used INT NOT NULL DEFAULT 0,
    customer_email TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create the uploads table
CREATE TABLE IF NOT EXISTS public.uploads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create the generations configuration table
CREATE TABLE IF NOT EXISTS public.generations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    theme_type TEXT NOT NULL,
    theme_details JSONB,
    nameplate TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    preview_urls JSONB,
    output_image_url TEXT,
    show_in_gallery BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Enable Row Level Security (RLS) but allow anonymous access for demo
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.uploads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.generations ENABLE ROW LEVEL SECURITY;

-- Policies for orders (idempotent: drop-then-create)
DROP POLICY IF EXISTS "Enable read access for all users" ON public.orders;
CREATE POLICY "Enable read access for all users" ON public.orders FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable insert access for all users" ON public.orders;
CREATE POLICY "Enable insert access for all users" ON public.orders FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Enable update access for all users" ON public.orders;
CREATE POLICY "Enable update access for all users" ON public.orders FOR UPDATE USING (true);

-- Policies for uploads
DROP POLICY IF EXISTS "Enable read access for all users" ON public.uploads;
CREATE POLICY "Enable read access for all users" ON public.uploads FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable insert access for all users" ON public.uploads;
CREATE POLICY "Enable insert access for all users" ON public.uploads FOR INSERT WITH CHECK (true);

-- Policies for generations
DROP POLICY IF EXISTS "Enable read access for all users" ON public.generations;
CREATE POLICY "Enable read access for all users" ON public.generations FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable insert access for all users" ON public.generations;
CREATE POLICY "Enable insert access for all users" ON public.generations FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Enable update access for all users" ON public.generations;
CREATE POLICY "Enable update access for all users" ON public.generations FOR UPDATE USING (true);

-- 5. Create Storage Bucket for user uploads
INSERT INTO storage.buckets (id, name, public) 
VALUES ('user-uploads', 'user-uploads', true) 
ON CONFLICT (id) DO NOTHING;

-- Storage Policies for 'user-uploads' bucket
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'user-uploads');

DROP POLICY IF EXISTS "Public Uploads" ON storage.objects;
CREATE POLICY "Public Uploads" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'user-uploads');
